abstract: Cronolog Model Class
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Catalyst-Model-Cronolog
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst::Devel: 0
version: 0.01
